import { createClient } from 'https://esm.sh/@supabase/supabase-js@2?target=deno&no-check';
import { resolveSupabaseUrl } from '../_shared/supabase.ts';
import { corsHeaders, jsonResponse, errorResponse } from '../_shared/cors.ts';

const SUPABASE_URL = resolveSupabaseUrl();

const handler = async (request: Request): Promise<Response> => {
  if (request.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const supabaseAdmin = createClient(
      SUPABASE_URL,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const { invoice_id } = await request.json();

    if (!invoice_id) {
      return errorResponse('Missing invoice_id');
    }

    const { data: invoice, error } = await supabaseAdmin
      .from('mushi_invoices')
      .select('*, customer:mushi_customers(email, first_name, last_name), payment:mushi_payments(provider_payment_id)')
      .eq('id', invoice_id)
      .single();

    if (error || !invoice) {
      return errorResponse('Invoice not found', 404);
    }

    // Generate a simple HTML invoice that can be printed to PDF
    const html = generateInvoiceHtml(invoice);

    return new Response(html, {
      status: 200,
      headers: {
        ...corsHeaders,
        'Content-Type': 'text/html; charset=utf-8',
      },
    });
  } catch (err) {
    console.error('Error in mushi-generate-invoice-pdf:', err);
    return errorResponse(err.message, 500);
  }
};

function generateInvoiceHtml(invoice: Record<string, unknown>): string {
  const customer = invoice.customer as Record<string, string>;
  const lineItems = (invoice.line_items as Array<{ description: string; amount: number; quantity: number }>) || [];
  const date = new Date(invoice.created_at as string).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Invoice ${invoice.invoice_number}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #333; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; }
    .brand { font-size: 24px; font-weight: bold; color: #6d28d9; }
    .invoice-meta { text-align: right; }
    .invoice-meta h2 { margin: 0; font-size: 28px; color: #1a1a1a; }
    .details { display: flex; justify-content: space-between; margin-bottom: 40px; }
    .details div { font-size: 14px; line-height: 1.6; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    th { background: #f8f8f8; text-align: left; padding: 12px; border-bottom: 2px solid #e5e5e5; font-size: 14px; }
    td { padding: 12px; border-bottom: 1px solid #e5e5e5; font-size: 14px; }
    .total-row td { font-weight: bold; font-size: 16px; border-top: 2px solid #333; }
    .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #999; }
    @media print { body { padding: 0; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">MushiHost</div>
    <div class="invoice-meta">
      <h2>INVOICE</h2>
      <p><strong>${invoice.invoice_number}</strong></p>
      <p>Date: ${date}</p>
      <p>Status: ${(invoice.status as string).toUpperCase()}</p>
    </div>
  </div>
  <div class="details">
    <div>
      <strong>Bill To:</strong><br>
      ${customer?.first_name || ''} ${customer?.last_name || ''}<br>
      ${customer?.email || ''}
    </div>
    <div>
      <strong>From:</strong><br>
      MushiHost Payments<br>
      payments@mushihost.com
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th style="text-align:center">Qty</th>
        <th style="text-align:right">Amount</th>
      </tr>
    </thead>
    <tbody>
      ${lineItems.map((item) => `
        <tr>
          <td>${item.description}</td>
          <td style="text-align:center">${item.quantity}</td>
          <td style="text-align:right">$${Number(item.amount).toFixed(2)}</td>
        </tr>
      `).join('')}
      <tr>
        <td colspan="2" style="text-align:right">Subtotal</td>
        <td style="text-align:right">$${Number(invoice.amount_usd).toFixed(2)}</td>
      </tr>
      <tr>
        <td colspan="2" style="text-align:right">Tax</td>
        <td style="text-align:right">$${Number(invoice.tax_usd || 0).toFixed(2)}</td>
      </tr>
      <tr class="total-row">
        <td colspan="2" style="text-align:right">Total</td>
        <td style="text-align:right">$${Number(invoice.total_usd).toFixed(2)}</td>
      </tr>
    </tbody>
  </table>
  <div class="footer">
    <p>Thank you for your purchase. This invoice was generated by MushiHost.</p>
  </div>
</body>
</html>`;
}

Deno.serve(handler);
